In [104]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from astropy.io import fits
from astropy.table import Table
ruta_fits = 'BlazEr1_catalog.fits'

In [105]:
with fits.open(ruta_fits) as arc:
    print("--- Estructura de BlazEr1---")
    arc.info() #Info general del archivo

--- Estructura de BlazEr1---
Filename: BlazEr1_catalog.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       6   ()
  1  BLAZER1       1 BinTableHDU   2379   5865R x 661C   [29A, D, D, 5A, D, 32A, 15A, 21A, 20A, 26A, 29A, 28A, 14A, 17A, D, 32A, 23A, J, J, K, K, J, D, 1PE(2), D, 1PE(2), D, D, D, D, D, D, D, D, E, E, E, E, E, 1PE(2), E, E, E, E, 1PE(2), E, E, 1PE(2), E, E, 1PE(2), E, E, E, J, E, E, E, E, E, E, E, 1PE(2), E, E, 1PE(2), E, E, 1PE(2), E, E, E, J, E, E, E, E, E, E, E, 1PE(2), E, E, 1PE(2), E, E, 1PE(2), E, E, E, J, E, E, E, E, E, E, E, 1PE(2), E, E, 1PE(2), E, E, 1PE(2), E, E, E, J, E, E, E, E, E, E, E, 1PE(2), E, E, 1PE(2), E, E, 1PE(2), E, E, E, J, E, E, E, E, E, E, E, 1PE(2), E, E, 1PE(2), E, E, 1PE(2), E, E, E, J, E, E, E, E, E, E, E, 1PE(2), E, E, 1PE(2), E, E, 1PE(2), E, E, E, J, E, E, E, E, E, E, E, 1PE(2), E, E, 1PE(2), E, E, 1PE(2), E, E, E, J, E, E, E, E, E, E, E, 1PE(2), E, E, 1PE(2), E, E, 1PE(2), E, E, E, J, E, E, E, E, E, E, E, 1PE(2), E, E, 1PE(2), E, E, 1PE(2), E, E, E, J, E, E, E, E, J, E, E, E, I, I, I, I, I, I, I, I, I, D, 1PE(2), D, 1PE(2), D, D, D, D, D, D, 1PE(2), D, 1PE(2), D, 1PE(2), D, 1PE(2), D, 1PE(2), D, 1PE(2), D, D, D, D, J, J, J, D, 1PE(2), D, 1PE(2), D, 1PE(2), D, D, D, D, J, J, J, D, 1PE(2), D, 1PE(2), D, 1PE(2), D, D, D, D, J, J, J, D, 1PE(2), D, 1PE(2), D, 1PE(2), D, D, D, D, J, J, J, D, D, D, 1PE(2), D, 1PE(2), D, 1PE(2), D, 1PE(2), D, 1PE(2), D, D, D, D, J, J, J, D, D, 1PE(2), D, 1PE(2), D, 1PE(2), D, 1PE(2), D, D, D, D, J, J, J, D, D, D, D, D, D, D, 22A, D, D, D, D, D, 1PE(2), D, 1PE(2), D, 1PE(2), D, 1PE(2), D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, 18A, D, D, 17A, D, D, D, D, D, D, D, D, D, D, D, D, D, 32A, D, D, D, D, 32A, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, 32A, D, D, D, D, D, D, 32A, D, 32A, D, 32A, D, 32A, D, 32A, D, 32A, D, 32A, D, 32A, D, 32A, D, 32A, D, 32A, 32A, 32A, D, 32A, 32A, D, D, D, D, D, D, D, D, D, D, 18A, 48A, E, E, E, D, E, E, E, E, E, E, D, 3A, 62A, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, I, I, E, E, E, I, I, E, E, E, I, I, E, E, E, I, I, E, E, E, B, E, E, E, B, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, 2A, K, E, E, E, E, E, E, E, E, E, E, 5A, D, D, D, D, D, D, D, D, D, D, D, D, D, 5A, 5A, 5A, 31A, D, D, D, D, D, D, 30A, D, D, E, E, E, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, 38A, D, D, D, D, D, 56A, D, D, D, 32A, D, 32A, D, D, D, D, 13A, D, 13A, D, 1PE(2), D, 1PE(2), D, D, D, D, D, D, D, D, D, D, D, D, 35A, 19A, 133A, 19A, D, 6A, 14A, 12A, 7A, 14A, D, D, D, D, D, D, 32A, 32A, 32A]

In [ ]:
tabla_astropy = Table.read(ruta_fits, hdu=1)
df = tabla_astropy.to_pandas()
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# Ahora, para listar todas las columnas de corrido:
print(df.columns.tolist())
print(df.)

WARNING: UnitsWarning: 'sigma' did not parse as fits unit: At col 0, Unit 'sigma' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'sigma' did not parse as fits unit: At col 0, Unit 'sigma' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy^(-2)' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy^(-2)' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy^(-2)' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy^(-2)' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy^(-2)' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy^(-2)' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy^(-2)' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy^(-2)' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy^(-2)' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy^(-2)' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy^(-2)' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy^(-2)' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy^(-2)' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy^(-2)' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy^(-2)' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy^(-2)' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy^(-2)' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'nanomaggy^(-2)' did not parse as fits unit: At col 0, Unit 'nanomaggy' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]

['SRC_NAME', 'RAJ2000', 'DECJ2000', 'BLAZAR_CLASS', 'CONF_BLAZAR', 'FGL_SRC_NAME', 'BZCAT_SRC_NAME', 'HSP_SRC_NAME', 'HIGHZ_SRC_NAME', 'MILLIQUAS_SRC_NAME', 'KDEBLLACS_SRC_NAME', 'WIBRALS2_SRC_NAME', 'ABC_SRC_NAME', 'BROS_SRC_NAME', 'ANGSEP', 'DETUID', 'IAUNAME', 'SKYTILE', 'ID_SRC', 'UID', 'UID_HARD', 'ID_CLUSTER', 'RA', 'RA_ERR', 'DEC', 'DEC_ERR', 'RA_RAW', 'DEC_RAW', 'POS_ERR', 'RADEC_ERR', 'LII', 'BII', 'ELON', 'ELAT', 'MJD', 'MJD_MIN', 'MJD_MAX', 'EXT', 'EXT_ERR', 'EXT_ASYM_ERR', 'EXT_LIKE', 'DET_LIKE_0', 'ML_CTS_1', 'ML_CTS_1_ERR', 'ML_CTS_1_ASYM_ERR', 'ML_RATE_1', 'ML_RATE_1_ERR', 'ML_RATE_1_ASYM_ERR', 'ML_FLUX_1', 'ML_FLUX_1_ERR', 'ML_FLUX_1_ASYM_ERR', 'ML_BKG_1', 'ML_EXP_1', 'ML_EEF_1', 'APE_CTS_1', 'APE_BKG_1', 'APE_EXP_1', 'APE_RADIUS_1', 'APE_POIS_1', 'DET_LIKE_P1', 'ML_CTS_P1', 'ML_CTS_P1_ERR', 'ML_CTS_P1_ASYM_ERR', 'ML_RATE_P1', 'ML_RATE_P1_ERR', 'ML_RATE_P1_ASYM_ERR', 'ML_FLUX_P1', 'ML_FLUX_P1_ERR', 'ML_FLUX_P1_ASYM_ERR', 'ML_BKG_P1', 'ML_EXP_P1', 'ML_EEF_P1', 'APE_CTS_P1', 'APE_BKG_P1', 'APE_EXP_P1', 'APE_RADIUS_P1', 'APE_POIS_P1', 'DET_LIKE_P2', 'ML_CTS_P2', 'ML_CTS_P2_ERR', 'ML_CTS_P2_ASYM_ERR', 'ML_RATE_P2', 'ML_RATE_P2_ERR', 'ML_RATE_P2_ASYM_ERR', 'ML_FLUX_P2', 'ML_FLUX_P2_ERR', 'ML_FLUX_P2_ASYM_ERR', 'ML_BKG_P2', 'ML_EXP_P2', 'ML_EEF_P2', 'APE_CTS_P2', 'APE_BKG_P2', 'APE_EXP_P2', 'APE_RADIUS_P2', 'APE_POIS_P2', 'DET_LIKE_P3', 'ML_CTS_P3', 'ML_CTS_P3_ERR', 'ML_CTS_P3_ASYM_ERR', 'ML_RATE_P3', 'ML_RATE_P3_ERR', 'ML_RATE_P3_ASYM_ERR', 'ML_FLUX_P3', 'ML_FLUX_P3_ERR', 'ML_FLUX_P3_ASYM_ERR', 'ML_BKG_P3', 'ML_EXP_P3', 'ML_EEF_P3', 'APE_CTS_P3', 'APE_BKG_P3', 'APE_EXP_P3', 'APE_RADIUS_P3', 'APE_POIS_P3', 'DET_LIKE_P4', 'ML_CTS_P4', 'ML_CTS_P4_ERR', 'ML_CTS_P4_ASYM_ERR', 'ML_RATE_P4', 'ML_RATE_P4_ERR', 'ML_RATE_P4_ASYM_ERR', 'ML_FLUX_P4', 'ML_FLUX_P4_ERR', 'ML_FLUX_P4_ASYM_ERR', 'ML_BKG_P4', 'ML_EXP_P4', 'ML_EEF_P4', 'APE_CTS_P4', 'APE_BKG_P4', 'APE_EXP_P4', 'APE_RADIUS_P4', 'APE_POIS_P4', 'DET_LIKE_P5', 'ML_CTS_P5', 'ML_CTS_P5_ERR', 'ML_CTS_P5_ASYM_ERR', 'ML_RATE_P5', 'ML_RATE_P5_ERR', 'ML_RATE_P5_ASYM_ERR', 'ML_FLUX_P5', 'ML_FLUX_P5_ERR', 'ML_FLUX_P5_ASYM_ERR', 'ML_BKG_P5', 'ML_EXP_P5', 'ML_EEF_P5', 'APE_CTS_P5', 'APE_BKG_P5', 'APE_EXP_P5', 'APE_RADIUS_P5', 'APE_POIS_P5', 'DET_LIKE_P6', 'ML_CTS_P6', 'ML_CTS_P6_ERR', 'ML_CTS_P6_ASYM_ERR', 'ML_RATE_P6', 'ML_RATE_P6_ERR', 'ML_RATE_P6_ASYM_ERR', 'ML_FLUX_P6', 'ML_FLUX_P6_ERR', 'ML_FLUX_P6_ASYM_ERR', 'ML_BKG_P6', 'ML_EXP_P6', 'ML_EEF_P6', 'APE_CTS_P6', 'APE_BKG_P6', 'APE_EXP_P6', 'APE_RADIUS_P6', 'APE_POIS_P6', 'DET_LIKE_P7', 'ML_CTS_P7', 'ML_CTS_P7_ERR', 'ML_CTS_P7_ASYM_ERR', 'ML_RATE_P7', 'ML_RATE_P7_ERR', 'ML_RATE_P7_ASYM_ERR', 'ML_FLUX_P7', 'ML_FLUX_P7_ERR', 'ML_FLUX_P7_ASYM_ERR', 'ML_BKG_P7', 'ML_EXP_P7', 'ML_EEF_P7', 'APE_CTS_P7', 'APE_BKG_P7', 'APE_EXP_P7', 'APE_RADIUS_P7', 'APE_POIS_P7', 'DET_LIKE_P8', 'ML_CTS_P8', 'ML_CTS_P8_ERR', 'ML_CTS_P8_ASYM_ERR', 'ML_RATE_P8', 'ML_RATE_P8_ERR', 'ML_RATE_P8_ASYM_ERR', 'ML_FLUX_P8', 'ML_FLUX_P8_ERR', 'ML_FLUX_P8_ASYM_ERR', 'ML_BKG_P8', 'ML_EXP_P8', 'ML_EEF_P8', 'APE_CTS_P8', 'APE_BKG_P8', 'APE_EXP_P8', 'APE_RADIUS_P8', 'APE_POIS_P8', 'DET_LIKE_P9', 'ML_CTS_P9', 'ML_CTS_P9_ERR', 'ML_CTS_P9_ASYM_ERR', 'ML_RATE_P9', 'ML_RATE_P9_ERR', 'ML_RATE_P9_ASYM_ERR', 'ML_FLUX_P9', 'ML_FLUX_P9_ERR', 'ML_FLUX_P9_ASYM_ERR', 'ML_BKG_P9', 'ML_EXP_P9', 'ML_EEF_P9', 'APE_CTS_P9', 'APE_BKG_P9', 'APE_EXP_P9', 'APE_RADIUS_P9', 'APE_POIS_P9', 'APE_CTS_S', 'APE_BKG_S', 'APE_EXP_S', 'APE_POIS_S', 'FLAG_SP_SNR', 'FLAG_SP_BPS', 'FLAG_SP_SCL', 'FLAG_SP_LGA', 'FLAG_SP_GC_CONS', 'FLAG_NO_RADEC_ERR', 'FLAG_NO_EXT_ERR', 'FLAG_NO_CTS_ERR', 'FLAG_OPT', 'CTS_1', 'CTS_1_ERR', 'CTS_T', 'CTS_T_ERR', 'SPEC_EXPOTIME', 'EXPOTIME', 'MIN_FLUX_95', 'AVERAGE_NH', 'WE_AVERAGE_NH', 'HR12', 'HR12_ERR', 'HR23', 'HR23_ERR', 'HR13', 'HR13_ERR', 'PWL15_NORM', 'PWL15_NORM_ERR', 'PWL15_FLUX_UNABS_0', 'PWL15_FLUX_UNABS_0_ERR', 'PWL15_FLUX_ABS_0', 'PWL15_FLUX_ABS_0_ERR', 'PWL15_C_VARIANCE', 'PWL15_CASH', 'PWL15_CSTAT_THEORY', 'PWL15_REDCASH', 'PWL15_CASHBINS', 'PWL15_CASHPAR', 'PWL15_NUM_BINS', 'PWL17_NORM', 'PWL17_NORM_ERR', 'PWL17_FLUX_UNABS_0', 'PWL17_FLUX_UNABS_0_ERR', 'PWL17_FLUX_ABS_0', 'PWL17_FLUX_ABS_0_ERR', 'PWL17_C_VARIANCE', 'PWL17_CASH', 'PWL17_CSTAT_THEORY', 'PWL17_REDCASH', 'PWL17_CASHBINS', 'PWL17_CASHPAR', 'PWL17_NUM_BINS', 'PWL20_NORM', 'PWL20_NORM_ERR', 'PWL20_FLUX_UNABS_0', 'PWL20_FLUX_UNABS_0_ERR', 'PWL20_FLUX_ABS_0', 'PWL20_FLUX_ABS_0_ERR', 'PWL20_C_VARIANCE', 'PWL20_CASH', 'PWL20_CSTAT_THEORY', 'PWL20_REDCASH', 'PWL20_CASHBINS', 'PWL20_CASHPAR', 'PWL20_NUM_BINS', 'PWL23_NORM', 'PWL23_NORM_ERR', 'PWL23_FLUX_UNABS_0', 'PWL23_FLUX_UNABS_0_ERR', 'PWL23_FLUX_ABS_0', 'PWL23_FLUX_ABS_0_ERR', 'PWL23_C_VARIANCE', 'PWL23_CASH', 'PWL23_CSTAT_THEORY', 'PWL23_REDCASH', 'PWL23_CASHBINS', 'PWL23_CASHPAR', 'PWL23_NUM_BINS', 'FLUX_JY', 'FLUX_JY_ERR', 'FREE_NH', 'FREE_NH_ERR', 'FREE_GAMMA', 'FREE_GAMMA_ERR', 'FREE_NORM', 'FREE_NORM_ERR', 'FREE_FLUX_UNABS_0', 'FREE_FLUX_UNABS_0_ERR', 'FREE_FLUX_ABS_0', 'FREE_FLUX_ABS_0_ERR', 'FREE_C_VARIANCE', 'FREE_CASH', 'FREE_CSTAT_THEORY', 'FREE_REDCASH', 'FREE_CASHBINS', 'FREE_CASHPAR', 'FREE_NUM_BINS', 'FIXED_NH', 'FIXED_GAMMA', 'FIXED_GAMMA_ERR', 'FIXED_NORM', 'FIXED_NORM_ERR', 'FIXED_FLUX_UNABS_0', 'FIXED_FLUX_UNABS_0_ERR', 'FIXED_FLUX_ABS_0', 'FIXED_FLUX_ABS_0_ERR', 'FIXED_C_VARIANCE', 'FIXED_CASH', 'FIXED_CSTAT_THEORY', 'FIXED_REDCASH', 'FIXED_CASHBINS', 'FIXED_CASHPAR', 'FIXED_NUM_BINS', 'RXS_RA', 'RXS_DEC', 'RXS_NH_GAL', 'RXS_NH', 'RXS_GAMMA', 'RXS_GAMMA_ERR', 'RXS_FLUX_U', 'XRT_SRC_NAME', 'XRT_RA', 'XRT_DEC', 'XRT_ANGSEP', 'XRT_FLAG', 'XRT_NH', 'XRT_NH_ERR', 'XRT_GAMMA', 'XRT_GAMMA_ERR', 'XRT_ABS_FLUX_V', 'XRT_ABS_FLUX_V_ERR', 'XRT_UNABS_FLUX_V', 'XRT_UNABS_FLUX_V_ERR', 'OUSXB_RA', 'OUSXB_DEC', 'OUSXB_MIN_FLUX_V', 'OUSXB_MAX_FLUX_V', 'OUSXB_MEAN_FLUX_V', 'OUSXB_MEDIAN_FLUX_V', 'OUSXB_N_FLUX_V', 'OUSXB_MIN_GAMMA', 'OUSXB_MAX_GAMMA', 'OUSXB_MEAN_GAMMA', 'OUSXB_MEDIAN_GAMMA', 'OUSXB_N_GAMMA', 'NUSTAR_RA', 'NUSTAR_DEC', 'NUSTAR_GAMMA', 'NUSTAR_GAMMA_ERR', 'NUSTAR_FLUX_X', 'NUSTAR_FLUX_X_ERR', 'NUSTAR_FLUX_Y', 'NUSTAR_FLUX_Y_ERR', 'BAT_SRC_NAME', 'BAT_RA', 'BAT_DEC', 'BAT_TYPE', 'BAT_FLUX_Z', 'BAT_MIN_FLUX_Z', 'BAT_MAX_FLUX_Z', 'BAT_GAMMA', 'BAT_MIN_GAMMA', 'BAT_MAX_GAMMA', 'ASCAMASTER_EXPOTIME', 'CHANMASTER_EXPOTIME', 'NUMASTER_EXPOTIME', 'SUZAMASTER_EXPOTIME', 'XMMMASTER_EXPOTIME', 'SWIFTMASTR_EXPOTIME', 'ROSMASTER_EXPOTIME', 'FGL_COMMON_SRC_NAME', 'FGL_FLUX_B', 'FGL_FLUX_B_ERR', 'FGL_FLUX_A', 'FGL_FLUX_A_ERR', 'FGL_SPEC_TYPE', 'FGL_PL_FLUXDEN', 'FGL_PL_FLUXDEN_ERR', 'FGL_PL_INDEX', 'FGL_PL_INDEX_ERR', 'FGL_LP_FLUXDEN', 'FGL_LP_FLUXDEN_ERR', 'FGL_LP_INDEX', 'FGL_LP_INDEX_ERR', 'FGL_LP_BETA', 'FGL_LP_BETA_ERR', 'FGL_LP_EPEAK', 'FGL_LP_EPEAK_ERR', 'FGL_LP_SIGCURV', 'FGL_PLEC_FLUXDEN', 'FGL_PLEC_FLUXDEN_ERR', 'FGL_PLEC_INDEX', 'FGL_PLEC_INDEX_ERR', 'FGL_PLEC_EXPFACTOR', 'FGL_PLEC_EXPFACTOR_ERR', 'FGL_PLEC_EXPINDEX', 'FGL_PLEC_EXPINDEX_ERR', 'FGL_PLEC_EPEAK', 'FGL_PLEC_EPEAK_ERR', 'FGL_PLEC_SIGCURV', 'LAC_SED_CLASS', 'LAC_HE_EPEAK', 'LAC_HE_EPEAK_ERR', 'LAC_HE_NUFNU', 'LAC_HE_NUFNU_ERR', 'LAC_LE_FREQ', 'LAC_LE_NUFNU', 'RFC_SRC_NAME', 'RFC_SBAND_RES', 'RFC_SUPPER_RES', 'RFC_SBAND_UNRES', 'RFC_SUPPER_UNRES', 'RFC_CBAND_RES', 'RFC_CUPPER_RES', 'RFC_CBAND_UNRES', 'RFC_CUPPER_UNRES', 'RFC_XBAND_RES', 'RFC_XUPPER_RES', 'RFC_XBAND_UNRES', 'RFC_XUPPER_UNRES', 'RFC_UBAND_RES', 'RFC_UUPPER_RES', 'RFC_UBAND_UNRES', 'RFC_UUPPER_UNRES', 'RFC_KBAND_RES', 'RFC_KUPPER_RES', 'RFC_KBAND_UNRES', 'RFC_KUPPER_UNRES', 'TANAMI_SRC_NAME', 'TANAMI_CLASS', 'TANAMI_FLUX', 'MOJAVE_SRC_NAME', 'MOJAVE_CLASS', 'MOJAVE_FLUX', 'N_MATCH', 'LS10_SEP', 'LS10_USE', 'LS10_RELEASE', 'LS10_BRICKID', 'LS10_OBJID', 'LS10_RA', 'LS10_DEC', 'LS10_Xray_proba', 'LS10_FULLID', 'ERO_LS10_FULLID', 'LS10_RA_IVAR', 'LS10_DEC_IVAR', 'SEPARATION_LS10_ERO', 'NCAT', 'DIST_BAYESFACTOR', 'DIST_POST', 'BIAS_LS10_XRAY_PROBA', 'P_SINGLE', 'P_ANY', 'P_I', 'MATCH_FLAG', 'TYPE', 'LS10_DCHISQ', 'EBV', 'FLUX_G', 'FLUX_IVAR_G', 'MW_TRANSMISSION_G', 'FLUX_R', 'FLUX_IVAR_R', 'MW_TRANSMISSION_R', 'FLUX_I', 'FLUX_IVAR_I', 'MW_TRANSMISSION_I', 'FLUX_Z', 'FLUX_IVAR_Z', 'MW_TRANSMISSION_Z', 'FLUX_W1', 'FLUX_IVAR_W1', 'MW_TRANSMISSION_W1', 'FLUX_W2', 'FLUX_IVAR_W2', 'MW_TRANSMISSION_W2', 'FLUX_W3', 'FLUX_IVAR_W3', 'MW_TRANSMISSION_W3', 'FLUX_W4', 'FLUX_IVAR_W4', 'MW_TRANSMISSION_W4', 'ANYMASK_G', 'ALLMASK_G', 'PSFSIZE_G', 'PSFDEPTH_G', 'GALDEPTH_G', 'ANYMASK_R', 'ALLMASK_R', 'PSFSIZE_R', 'PSFDEPTH_R', 'GALDEPTH_R', 'ANYMASK_I', 'ALLMASK_I', 'PSFSIZE_I', 'PSFDEPTH_I', 'GALDEPTH_I', 'ANYMASK_Z', 'ALLMASK_Z', 'PSFSIZE_Z', 'PSFDEPTH_Z', 'GALDEPTH_Z', 'WISEMASK_W1', 'PSFDEPTH_W1', 'W1_MAG_AB', 'W1_MAG', 'WISEMASK_W2', 'PSFDEPTH_W2', 'W2_MAG_AB', 'W2_MAG', 'W3_MAG_AB', 'W3_MAG', 'W4_MAG_AB', 'W4_MAG', 'SHAPE_R', 'SHAPE_R_IVAR', 'SHAPE_E1', 'SHAPE_E1_IVAR', 'SHAPE_E2', 'SHAPE_E2_IVAR', 'SERSIC', 'SERSIC_IVAR', 'REF_CAT', 'REF_ID', 'REF_EPOCH', 'GAIA_PHOT_G_MEAN_MAG', 'GAIA_PHOT_G_MEAN_FLUX_OVER_ERROR', 'GAIA_PHOT_BP_MEAN_MAG', 'GAIA_PHOT_BP_MEAN_FLUX_OVER_ERROR', 'GAIA_PHOT_RP_MEAN_MAG', 'GAIA_PHOT_RP_MEAN_FLUX_OVER_ERROR', 'GAIA_ASTROMETRIC_EXCESS_NOISE', 'GAIA_PHOT_BP_RP_EXCESS_FACTOR', 'GAIA_ASTROMETRIC_SIGMA5D_MAX', 'GAIA_DUPLICATED_SOURCE', 'INALLLS10', 'INANYLS10', 'DERED_MAG_W1', 'DERED_MAG_W2', 'DERED_MAG_G', 'DERED_MAG_R', 'DERED_MAG_Z', 'SOFTFLUX_S', 'SALVATO18_W1_X_LINEDISTANCE', 'SALVATO22_ZW1_GR_LINEDISTANCE', 'G_MINUS_R', 'Z_MINUS_W1', 'W1_MINUS_W2', 'HAS_SALVATO18_AGN_COLORS', 'GAIA_MOVING_5SIGMA', 'HAS_SALVATO22_AGN_COLORS', 'SALVATO_MAIN_ID_SIMBAD', 'SALVATO_RA_SIMBAD', 'SALVATO_DEC_SIMBAD', 'EXGAL_PROB_GAIA_STAREX', 'EXGAL_PROB_STAREX', 'CLASS_GAL_EXGAL', 'SALVATO_HECATE', 'SALVATO_HEC_OBJNAME', 'SALVATO_HEC_RA', 'SALVATO_HEC_DEC', 'SALVATO_HEC_R1', 'SALVATO_HEC_R2', 'SALVATO_HEC_PA', 'PURITY6', 'COMPLETENESS6', 'COMPUR6', 'THRESHOLD6', 'PURITY7', 'COMPLETENESS7', 'COMPUR7', 'THRESHOLD7', 'PURITY8', 'COMPLETENESS8', 'COMPUR8', 'THRESHOLD8', 'Z_PHOTO_S3L', 'Z_PHOTO_S3U', 'Z_PHOTO_S1L', 'Z_PHOTO_S1U', 'Z_PHOTO', 'Z_SPEC', 'Z_SPEC_REF', 'Z_ABC', 'Z_3HSP', 'Z_F_3HSP', 'Z_MILLIQUAS', 'Z_HIGHZ', 'Z_HIGHZ_REF', 'Z_MOJAVE', 'Z_4LAC', 'Z_BZCAT', 'Z_U_BZCAT', 'Z_CGRABS', 'Z_F_CGRABS', 'Z_VERONCAT', 'Z_VERONCAT_QSO', 'Z_SIMBAD', 'Z_MASTER', 'Z_MASTER_REF', 'Z_MASTER_PHOTO', 'Z_MASTER_PHOTO_REF', 'XRAY_LUM_PHOTO_1', 'XRAY_LUM_PHOTO_1_ERR', 'XRAY_LUM_1', 'XRAY_LUM_1_ERR', 'ALPHA_XG', 'ALPHA_XG_ERR', 'ALPHA_IRX', 'ALPHA_IRX_ERR', 'ALPHA_OX', 'ALPHA_OX_ERR', 'ALPHA_RX', 'ALPHA_RX_ERR', 'ALPHA_TANAMI', 'ALPHA_TANAMI_ERR', 'ALPHA_MOJAVE', 'ALPHA_MOJAVE_ERR', 'SIMBAD_SRC_NAME', 'SIMBAD_TYPE', 'SIMBAD_ALT_TYPES', 'SIMBAD_TYPE2', 'SIMBAD_ANGSEP', 'CAMBRIDGE_SRC_NAME', 'PARKS_SRC_NAME', 'TEXAS_SRC_NAME', 'EINSTEIN_SRC_NAME', 'COMMON_SRC_NAME', 'BZCAT_RMAG', 'BZCAT_FR', 'BZCAT_F143', 'BZCAT_FLUX_U', 'BZCAT_FLUX_B', 'BZCAT_ALPHA_RO', 'XIE_MORPH_BZCAT', 'XIE_MORPH_KDEBLLACS', 'XIE_MORPH_WIBRALS']

In [107]:
df['BLAZAR_CLASS'].unique()

array([b'bcu  ', b'bll  ', b'fsrq ', b'bzg  ', b'bllc ', b'fsrqc',
       b'bcuc '], dtype=object)

In [ ]:

columnas = ['BLAZAR_CLASS', 'FGL_SRC_NAME' ,'FGL_PL_INDEX', 'FGL_PL_INDEX_ERR', 'FREE_GAMMA', 'FREE_GAMMA_ERR', 'ML_CTS_1',] 

df_muestra = df[columnas].copy()
df_muestra = df_muestra[df_muestra['FREE_GAMMA'].notna()]
df_muestra = df_muestra[df_muestra['FREE_GAMMA_ERR'].notna()]
df_muestra = df_muestra[df_muestra['FGL_SRC_NAME'].notna()] #Descarta los blazares que no coinciden con eROSITA o están vacíos
df_muestra = df_muestra[df_muestra['FGL_SRC_NAME'] != '']
df_muestra = df_muestra[df_muestra['ML_CTS_1'] > 50] #Esto es para quitar las mediciones de eROSITA menores a 50 counts
print("Dimensiones de la muestra:", df_muestra.shape)
df_muestra.head()

Dimensiones de la muestra: (1269, 7)

,BLAZAR_CLASS,FGL_SRC_NAME,FGL_PL_INDEX,FGL_PL_INDEX_ERR,FREE_GAMMA,FREE_GAMMA_ERR,ML_CTS_1
0,b'bcu ',b'4FGL_J0001.6-4156 ',1.781085,0.063962,2.399167,"[-0.17117156, 0.20507514]",640.261597
1,b'bcu ',b'4FGL_J0003.1-5248 ',1.781021,0.066147,2.501480,"[-0.23354085, 0.27093565]",343.812500
9,b'bcu ',b'4FGL_J0032.5-4724 ',1.694125,0.163683,3.082444,"[-0.42883846, 0.58605003]",83.560867
12,b'bcu ',b'4FGL_J0049.5-4150 ',2.057240,0.157466,3.401565,"[-0.5567421, 0.55221]",68.427818
13,b'bcu ',b'4FGL_J0050.8-3428 ',1.945315,0.215441,2.275134,"[-0.3946951, 0.53194326]",90.257187

In [117]:
BZQ = df_muestra['BLAZAR_CLASS'] ==  b'fsrq '
df_1 = df_muestra[BZQ].copy()
df_1.head()

,BLAZAR_CLASS,FGL_SRC_NAME,FGL_PL_INDEX,FGL_PL_INDEX_ERR,FREE_GAMMA,FREE_GAMMA_ERR,ML_CTS_1
955,b'fsrq ',b'4FGL_J0023.7-6820 ',2.829112,0.064780,1.961880,"[-0.30787045, 0.4182908]",126.018112
959,b'fsrq ',b'4FGL_J0049.6-4500 ',2.689648,0.105093,2.188238,"[-0.34902146, 0.45816147]",108.394104
960,b'fsrq ',b'4FGL_J0050.0-5736 ',2.434874,0.028503,1.576191,"[-0.31256285, 0.32192817]",116.782669
964,b'fsrq ',b'4FGL_J0112.0-6634 ',2.725361,0.063922,1.797399,"[-0.32978338, 0.3730594]",123.991753
968,b'fsrq ',b'4FGL_J0126.0-2221 ',2.529519,0.072036,1.725797,"[-0.39548314, 0.5012269]",77.557808

In [118]:
BZB = df_muestra['BLAZAR_CLASS'] == b'bll  '
df_2 = df_muestra[BZB].copy()
df_2.head()

,BLAZAR_CLASS,FGL_SRC_NAME,FGL_PL_INDEX,FGL_PL_INDEX_ERR,FREE_GAMMA,FREE_GAMMA_ERR,ML_CTS_1
426,b'bll ',b'4FGL_J0002.1-6728 ',1.817964,0.070351,2.481154,"[-0.2488324, 0.36289087]",212.126968
427,b'bll ',b'4FGL_J0009.8-4317 ',2.124825,0.081628,3.025977,"[-0.4400523, 0.6614622]",72.716385
429,b'bll ',b'4FGL_J0014.1-5022 ',2.107366,0.081496,2.361000,"[-0.24691767, 0.29059595]",296.279785
431,b'bll ',b'4FGL_J0021.9-5140 ',2.018452,0.045290,2.604091,"[-0.3374154, 0.39249557]",165.242355
432,b'bll ',b'4FGL_J0026.6-4600 ',1.997174,0.089169,2.607424,"[-0.27657703, 0.3904862]",152.958679

In [119]:
print("El número total de BZQ es ", df_1.shape[0])
print("El número total de BZB es ", df_2.shape[0])
print("El número total de Blazares (BZQ y BZB) es ", df_1.shape[0] + df_2.shape[0])

El número total de BZQ es  220
El número total de BZB es  353
El número total de Blazares (BZQ y BZB) es  573